Practica2/PracticaWeb/PracticaWeb/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from rest_framework import routers

from forkilla import views

router = routers.DefaultRouter()
router.register(r'restaurants', views.RestaurantViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forkilla/', include('forkilla.urls')),
    url(r'', include('forkilla.urls')),

    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^forkilla/accounts/login/$', login, name='login'),
    url(r'^forkilla/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^reservations/accounts/login/$', login, name='login'),
    url(r'^reservations/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^reviews/accounts/login/$', login, name='login'),
    url(r'^reviews/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^details/accounts/login/$', login, name='login'),
    url(r'^details/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^restaurant/accounts/login/$', login, name='login'),
    url(r'^restaurant/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^comparator/accounts/login/$', login, name='login'),
    url(r'^comparator/accounts/logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.handler404
handler500 = views.handler500


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Practica2/PracticaWeb/forkilla/urls.py
from django.conf.urls import url

from . import views

listOfAddresses = ["sd2019-f2-forkilla.herokuapp.com", "sd2019-f4-forkilla.herokuapp.com", "sd2019-f8-forkilla.herokuapp.com",
                   "sd2019-forkillaf6.herokuapp.com","sd2019-f7-forkilla.herokuapp.com", "sd2019-forkillaf10.herokuapp.com"

                   ]
#listOfAddresses = ["localhost"]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^restaurants/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/(?P<category>.*)$', views.restaurants, name='restaurants'),
    url(r'^restaurant/(?P<restaurant_number>.*)', views.details, name='details'), # Poner el /
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^base/$', views.checkout, name='base'),
    url(r'^reviews/$', views.reviews, name='reviews'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_space/$', views.user_space, name='user_space'),
    url(r'^delreservation/$', views.delreservation, name='delreservation'),

    # url('restaurants/$', views.RestaurantList.as_view()),
    # url('restaurants/<int:pk>/', views.RestaurantDetail.as_view()),
    url(r'^comparator/$', views.comparator, {'ips': listOfAddresses}, name='comparator'),
]

# from django.conf.urls import include

# urlpatterns += [
#    url('api-auth/', include('rest_framework.urls')),
# ]

Practica2/PracticaWeb/forkilla/models.py
from django.db import models

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

from datetime import datetime


# Create your models here.


class Restaurant(models.Model):
    CATEGORIES = (
        ("Rice", "Rice"),
        ("Fusi", "Fusion"),
        ("BBQ", "Barbecue"),
        ("Chin", "Chinese"),
        ("Medi", "Mediterranean"),
        ("Crep", "Creperie"),
        ("Hind", "Hindu"),
        ("Japa", "Japanese"),
        ("Ital", "Italian"),
        ("Mexi", "Mexican"),
        ("Peru", "Peruvian"),
        ("Russ", "Russian"),
        ("Turk", "Turkish"),
        ("Basq", "Basque"),
        ("Vegy", "Vegetarian"),
        ("Afri", "African"),
        ("Egyp", "Egyptian"),
        ("Grek", "Greek")
    )
    _d_categories = dict(CATEGORIES)

    restaurant_number = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=50)
    menu_description = models.TextField()
    price_average = models.DecimalField(max_digits=5, decimal_places=2)
    is_promot = models.BooleanField()
    rate = models.DecimalField(default=0.0, max_digits=2, decimal_places=1,
                               validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    featured_photo = models.ImageField(upload_to="images/")
    category = models.CharField(max_length=5, choices=CATEGORIES)
    restaurant_capacity = models.PositiveIntegerField(validators=[MaxValueValidator(999)])

    def get_human_category(self):
        return self._d_categories[self.category]

    def __str__(self):
        return ('[**Promoted**]' if self.is_promot else '') + "[" + self.category + "] " \
                                                                                    "[" + self.restaurant_number + "] " + self.name + " - " + self.menu_description + " (" + str(
            self.rate) + ")" \
                         ": " + str(self.price_average) + u" €"


class Reservation(models.Model):
    SLOTS = (
        ("morning_first", "12h00"),
        ("morning_second", "13h00"),
        ("morning_third", "14h00"),
        ("morning_fourth", "15h00"),
        ("evening_first", "20h00"),
        ("evening_second", "21h00"),
        ("evening_third", "22h00"),
    )
    _d_slots = dict(SLOTS)

    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant)
    day = models.DateField(default=datetime.now)
    time_slot = models.CharField(max_length=15, choices=SLOTS)
    num_people = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)

    def get_human_slot(self):
        return self._d_slots[self.time_slot]

    def get_reservation_amount(self):
        return len(self._d_slots.get(0))


class ViewedRestaurants(models.Model):
    id_vr = models.AutoField(primary_key=True)
    restaurant = models.ManyToManyField(Restaurant, through='RestaurantInsertDate')


class RestaurantInsertDate(models.Model):
    viewedrestaurants = models.ForeignKey(ViewedRestaurants, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']


class Review(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant)
    review_title = models.CharField(max_length=50)
    review_comment = models.TextField(max_length=100)
    review_rate = models.DecimalField(default=1.0, max_digits=2, decimal_places=1,
                                      validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)


# todas las reviews de todos los restaurantes
class ExistingReviews(models.Model):
    id_review = models.AutoField(primary_key=True)
    reviews = models.ManyToManyField(Review)

Practica2/PracticaWeb/forkilla/forms.py
from django import forms

from .models import Reservation, Review


class ReservationForm(forms.ModelForm):


    class Meta:
        model = Reservation
        fields = ["day", "time_slot", "num_people"]


class ReviewForm(forms.ModelForm):


    class Meta:
        model = Review
        fields = ["review_rate", "review_title", "review_comment"]

Practica2/PracticaWeb/templates/forkilla/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>Base</title>
    <meta charset="utf-8">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'forkilla/css/style.css' %}">

</head>
<body>

    <nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'forkilla/images/logo1.png' %}" alt="logo" style="width:150px;">
            </a>

            <form class="from-inline" method="GET" action="" id="searchform">
                <input style="width: 300px" class="form-control mr-sm-3" type="text" id="searchbox" name="q" value="{{ request.GET.q }}" placeholder=" Search by city...">
            </form>



                <!-- Links -->
            <ul class="navbar-nav">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="accounts/login">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  href="register" style=" border-color: #01579b ;border:1px; border-style: solid;">Sign up</a>
                    </li>
                {% else %}
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            {{ user }}
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Your Profile</a>
                            <a class="dropdown-item" href="{% url 'user_space' %}">My reservations</a>
                            <a class="dropdown-item" href="accounts/logout">Sign out</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        {% block content %}
        {% endblock %}

        <br><br>
        {% if viewedrestaurants.restaurant.all %}
            <h2>Your last viewed Restaurants</h2>
            <br>
            <form action="{% url 'reservation'%}" method="get">
            {% csrf_token %}
            <div class="row text-center">
                {% for restaurant in viewedrestaurants.restaurantinsertdate_set.all|slice:"5"%}

                    <div class="col-lg-3 col-md-6 mb-4">
                        <div class="card h-100">
                             {% if restaurant.restaurant.featured_photo %}
                                <img class="card-img-top" src="{{ restaurant.restaurant.featured_photo.url }}" alt="">
                             {% endif %}

                            <div class="card-body">
                                <a href="{% url 'details' restaurant.restaurant.restaurant_number%}" >
                                    <h4 class="card-title">{{restaurant.restaurant.name}}</h4>
                                </a>
                                <p class="card-text">{{restaurant.restaurant.rate}} <img src="{% static 'forkilla/images/diamond.ico' %}" alt="diamond" style="width:17px;"></p>
                            </div>

                            <div class="card-footer">
                                <button class="btn btn-primary" type="submit" name="reservation" value={{restaurant.restaurant.restaurant_number}} > Book now!</button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            </form>
        {% endif %}
    </div>

</body>
</html>

Practica2/PracticaWeb/templates/forkilla/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% block content %}
    <br>
    <h4> Reservation Details: </h4>
    <ul>
        <li><a> Restaurant Number: {{ reservation.restaurant.restaurant_number }}</a></li>
        <li> <a> Restaurant Name: {{ reservation.restaurant.name }}</a></li>
        <li> <a> Restaurant Capacity: {{ reservation.restaurant.restaurant_capacity }}</a></li>
        <br>
        <li><a> Reservation Day: {{ reservation.day }}</a></li>
        <li><a> Reservation Hour: {{ reservation.time_slot }}</a></li>
        <li><a> Num People: {{ reservation.num_people }}</a></li>
    </ul>


    <br><br>

    {% endblock %}
</body>
</html>

Practica2/PracticaWeb/templates/forkilla/comparator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>F8-Ajax</title>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
     <script>

        function compare(ips){
            $("#output").html("");
            var output="";
            var parameters = new Map();
            var category = $("#category_selector").val();
            var city = $("#inputCity").val();
            var price = $("#inputPrice").val();



            if(category != ""){
                parameters.set('category', category);
            }
            if(city != ""){
                parameters.set('city', city);
            }
            if(price != ""){
                parameters.set('price', price);
            }

            var dir = "";
            var j = 0;
            for (var [clave, valor] of parameters) {
                if(j == 0){
                  dir +="?"+clave+"="+valor;
                }else{
                     dir +="&"+clave+"="+valor;
                }
                j++;
            }

            for(let i=0; i<ips.length; i++){
                $.ajax({

                    //url: 'http://' + ips[i] + ':8000/api/restaurants/'+dir,
                    url: 'https://' + ips[i] + '/api/restaurants/'+dir,
                    type: 'GET',
                    dataType: 'json',

		            success: function (data) {
                        output+= "Requested URL: " + this.url + "<br>";
                        output += '<pre id="json">';
                        data['results'].sort(function (a,b) {
                            return parseFloat(b.price_average) - parseFloat(a.price_average);
                        });
                        output += JSON.stringify(data['results'], undefined, 2);
                        output += "</pre>";
                        $("#output").append(output+"<hr>");
                    },

                    complete: function( xhr, status ) {
                        output = "";
                    },

                    error: function( xhr, status, errorThrown ) {
                        alert( "Sorry, there was a problem!" );
                        console.log( "Error: " + errorThrown );
                        console.log( "Status: " + status );
                        console.dir( xhr );
                    }
                });
            }
        }
        </script>

</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
    {% load static %}
        <br><br>
    <div class="form-group">
        <label for="sel2">Select a category: </label>
        <select class="form-control" id="category_selector">
            {% for category in categories %}
                <option>{{ category }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
      <label for="inputCity">Input a City: </label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <br>

    <div class="form-group">
      <label for="inputPrice">Input a Price: </label>
      <input type="text" class="form-control" id="inputPrice">
    </div>
    <br>
   <button class="btn btn-info btn-sm" onclick="compare({{ ips }})">Send Request! </button>
    <br><br>

    <div id=output class=""></div>
    {% endblock %}

</body>
</html>

Practica2/PracticaWeb/templates/forkilla/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% block content %}
    <br>
    {% if restaurant %}
        <li><a href="{% url 'index' %}forkilla">forkilla</a>/<a
                href="{% url 'restaurants' restaurant.city %}">{{restaurant.city}}</a>/<a
                href="{% url 'restaurants' restaurant.city restaurant.category %}">{{restaurant.category}}</a>/{{restaurant.name}}
            </li>

        <h4> Restaurant Number: {{ restaurant.restaurant_number }}</h4>
        <h4> Restaurant Name: {{ restaurant.name }}</h4>
        <h4> Restaurant Menu Description: {{ restaurant.menu_description }}</h4>
        <h4> Restaurant Prize Average: {{ restaurant.price_average }}</h4>
        <h4> Restaurant Is Promoted: {{ restaurant.is_promot }}</h4>
        <h4> Restaurant Rate: {{ restaurant.rate }}</h4>
        <h4> Restaurant Address: {{ restaurant.address }}</h4>
        <h4> Restaurant City: {{ restaurant.city }}</h4>
        <h4> Restaurant Country: {{ restaurant.country }}</h4>
        <h4> Restaurant Category: {{ restaurant.category }}</h4>
    {% endif %}

    <br>

    <h4>Reviews</h4>
    {% for review in reviews.all %}
        {% if review.restaurant.restaurant_number == restaurant.restaurant_number %}
            <ul>
                <li>
                    {{review.user}} <br>
                    Title   :  {{review.review_title}} <br>
                    Comment :  {{ review.review_comment}} <br>
                    Rating  :  {{review.review_rate}} <br>
                </li>
            </ul>
        {% endif %}
    {% endfor %}

    <form action="{% url 'reviews'%}" method="get">
    <button type="submit" class="btn btn-primary" name="review" value={{restaurant.restaurant_number}}> Make review</button>
    </form>

    {% endblock %}
</body>
</html>

Practica2/PracticaWeb/templates/forkilla/reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reservation</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
    <br><br>
    <h2> Starting reservation for restaurant {{restaurant.name}}</h2>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" >Save</button>
    </form>

    {% endblock %}
</body>
</html>

Practica2/PracticaWeb/templates/forkilla/restaurants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurants</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% block content %}
    {% load static %}

        <br>

        {% if city %}
             <li>
                 {% if category %}
                     <a href="{% url 'index' %}forkilla">forkilla</a>/<a href="{% url 'restaurants' city%}">{{ city }}</a>/{{ category }}
                 {% else %}
                     <a href="{% url 'index' %}forkilla">forkilla</a>/{{city}}
                 {% endif %}
             </li>
        {% endif %}

        {% if restaurants %}
            {% if promoted %}
                <br>
                <h2>Most Popular Restaurants</h2>
            {% else %}
                <br>
                <h2>Restaurants in {{ search_result }}</h2>
            {% endif %}
            <br>

            <form action="{% url 'reservation'%}" method="get">
            <div class="row text-center">

                {% for restaurant in restaurants %}
                    <div class="col-lg-4 col-md-4 mb-4">

                        <div class="card h-100">

                            {% if restaurant.featured_photo %}
                                <img class="card-img-top" src="{{ restaurant.featured_photo.url }}" alt="">
                            {% endif %}

                                <div class="card-body">
                                    <a href="{% url 'details' restaurant.restaurant_number%}" >
                                        <h4 class="card-title">{{restaurant.name}}</h4>
                                    </a>
                                    <p class="card-text">{{restaurant.rate}} <img src="{% static 'forkilla/images/diamond.ico' %}" alt="diamond" style="width:17px;"></p>
                                </div>

                                <div class="card-footer">
                                    <button class="btn btn-primary" type="submit" name="reservation" value={{restaurant.restaurant_number}} > Book now!</button>
                                </div>
                            </div>
                        </div>

                {% endfor %}
            </div>
            </form>
        {% else %}
            <p>No restaurants are available.</p>
        {% endif %}

    {% endblock %}
</body>
</html>

Practica2/PracticaWeb/templates/forkilla/reviews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reviews</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
    <br><br>
    <h2>{{ user.get_username }}</h2>
    <h2> Rate {{restaurant.name}}</h2>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>





    {% endblock %}
</body>
</html>

Practica2/PracticaWeb/templates/forkilla/user_space.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Space</title>
</head>
<body>
    {% extends 'forkilla/base.html' %}
    {% block content %}
        <br><br>
        {% if user_reservations.all %}
            <div class="container">
            <h2 style="alignment: center">{{ user }}´s reservations:</h2><br>
                <div class="row text-center">

                    {% for reservation in user_reservations.all %}
                        <div class="col-lg-4 col-md-4 mb-4">
                            <div class="card h-100">
                                 {% if reservation.restaurant.featured_photo %}
                                    <img class="card-img-top" src="{{ reservation.restaurant.featured_photo.url }}" alt="">
                                 {% endif %}
                                <div class="card-body">
                                    <h4>{{ reservation.restaurant.name }}</h4>
                                </div>
                                <p class="card-text">
                                    Reservation Day: {{ reservation.day }} <br>
                                    Reservation Hour: {{ reservation.time_slot }} <br>
                                    Num People: {{ reservation.num_people }}
                                </p>
                                 <div class="card-footer">
                                     <form action="{% url 'delreservation'%}" method="get">
                                    <button class="btn btn-primary" type="submit" name="delete_reservation"
                                            value={{reservation.id}} > Delete</button>
                                     </form>
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            </div>
       {% endif %}

    {% endblock %}
</body>
</html>